version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aftas
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"

  spring-app:
    build:
      context: ./AFTAS
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/aftas?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:

  spring-app-angular:
    build:
      context: ./Aftas_Frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - spring-app
